- name: Manually kick off insights-compliance
  hosts: _hosts
  tasks:
    - name: Run insights-client --compliance
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.command: insights-client --compliance
      become: true
      changed_when: false
