---
- name: Register RHEL system using Red Hat account and register insights client
  hosts: all
  tasks:
    - name: Register Red Hat Enterprise Linux 8 using Red Hat account credentials
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.shell: |
        subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach --force-register --enable insights-client
      register: rhel_register_result
      changed_when: rhel_register_result.rc == 0
      failed_when: rhel_register_result.rc != 0 and rhel_register_result.rc != 257