---
- name: Un-Register RHEL system using Red Hat account and register insights client
  hosts: _hosts
  tasks:
    - name: Unregister system from insights-client
      # Content suggestion provided by Ansible Lightspeed
      ansible.builtin.command:
        cmd: /usr/sbin/insights-client --unregister --force
      become: true
      become_user: root
      become_method: sudo
      register: unregister_system_result
      changed_when: unregister_system_result.rc == 0
      failed_when: unregister_system_result.rc != 0 and 'is not registered' not in unregister_system_result.stderr
